### ISSUE TITLE
_abort() food.c:43

### ISSUE THREAD

**Issue by kernell-xx** [comex/frash#26]
_abort() food.c:43
That's the error i get whenever i touch something with flash to be played; in my iPad with IOS 4.2.1.

**Comment by xxzedenxx** [comment]
same here i think they need to fix it for 4.2.1

**Comment by Hunter-Dolan** [comment]
I also see this with my iPhone 3GS 4.2.1 (Green Poison). Any ideas anyone?

**Comment by calaba** [comment]
**\* Warning **\* Even I have decades experience with development on various platforms/languages I am complete rookie in Mac OS/ iOS world ... so forbid any inaccuracies or other bulls_t I put below *_*

Ok guys, I got tired googling all over internet to get same output on this one -> means nothing, everyone just complains it doesn't work, none analyzes. Thus I had checked the source code of Fresh - food.c - line 43 - as some add function trying to lookp and initialize needed libraries - and here it is failing. So I scanned my /usr/lib and really some of referenced libraries were not found (also libraries referenced by other libraries), here is status update on my 4.2.1 iPad iOS:

1) can anyone who is responsible  for maintaing this git source add better error handling -> i.e. instead of dummy abort message display which library failed to load ... 

2) In the latest source code there is following sequence:

```
add("/usr/lib/libcrypto.dylib");   ----> don't have it
add("/usr/lib/libssl.dylib");      ----> don't have it
add("/usr/lib/libm.dylib");        ----> don't have it
add("/usr/lib/libSystem.B.dylib"); ----> don't have it

add("./libcutils.dylib");
add("./libutils.dylib");
add("./libgccstuff.dylib");
add("./libicudata.42.1.dylib");
add("./libicui18n.42.1.dylib");
add("./libicuio.42.1.dylib");
add("./libicule.42.1.dylib");
add("./libiculx.42.1.dylib");
add("./libicutu.42.1.dylib");
add("./libicuuc.42.1.dylib");

int fd = open("libflashplayer.so", O_RDONLY);
```

So as you see already 1st 4 libs were missing + anaylyzing the other libraries I also found other once also missing -> mainly libcrypt ang libgcc. 

Then I remind myself when trying to add GNU cc comipler from cydia I was facing issue that libgcc was missing -> whatever are the reasons. 

So reason for this problem is clear, question is if we can solve it or not, I started playing around and did:

A) I got libgcc and installed it from following repo (hope I am not mistaken as I tried too many repos recently :) - http://theworm.altervista.org/cydia/  - btw reffered from this thread http://modmyi.com/forums/iphone-ipod-touch-sdk-development-discussion/655111-compiling-iphone-3-0-a.html - other approaches are mentioned -> but read whole thread 1st !!!)

B) after that I was able to install bigboss GNU cc (and othe GNU libs) from Cydia ... I run gcc -> runs ok ... didn't tried yet to compile and run anything ... I looked into /usr/lib and saw lot of missing libs is now there -> sounds promissing ... 

C) got also header files refered from: http://antirez.com/page/iphone-gcc-guide.html - so I can start playing around whether the gcc will even work installed this way

Next plan:
- test whether GCC can compile hello world app and run it
- test whether the header files allow me to compile Frash-0.02 on the ipad directly ...if not -> then I'll try Xcode on Max OS .. 
- based on source code analysis of food.c check every referred library (and the libraries referred by the lib itself). If I could compile Frahs -> i'll try to add better error message stating which lib failed to load ...

I am busy man so if you can try to play around and post results here I'll appreciate it .. and dozens of other "iPad flash hunters" I guess ...

Cheers

**Comment by kernell-xx** [comment]
But, what if you take those missing .dylib from an old firmware?
Frash works fine in version 3.2.2, so it must have those files to work properly.

**Comment by kernell-xx** [comment]
I´ve closed the issue by mistake.
Now, i don´t know how to reopen it :(
Apparently, I can´t.....

**Comment by calaba** [comment]
Then create new one and past the all stuff back there :)

**Comment by calaba** [comment]
Ok, issue reopened as #28 here https://github.com/comex/frash/issues/closed/#issue/28
